### PR TITLE
added regex to properly strip out special characters the same as how …

### PR DESCRIPTION
**Pull request by aastrong**
…PHP drupal alias is doing

### CODE REVIEW

**Review by minorOffense — COMMENTED** [review]
Did you copy that regex Drupal?

**Comment by aastrong** [comment]
@minorOffense no i didnt copy the regex from Drupal - I couldnt find an exact regex to copy from.

**Comment by aastrong** [comment]
but is very simliar to some regex i found here
http://php.net/manual/en/function.preg-match.php

But does seem to be working - and i've tested this string:

test page ( { !@#$%^&* }) +- blah |\ <>?/ -- = _àáaâæãåā çćč èéêëēėę îïíīįì some test text ôöòóœøōõ ûüùúū ł ñń ßśš ÿ źžż

**Comment by minorOffense** [comment]
Can you add to the readme the source and expected result strings? Then I'll merge.

**Comment by aastrong** [comment]
@minorOffense - i created a readme - in this PR
https://github.com/CityofOttawa/bootstrap-toc/pull/2

Please let me know if this is okay - and ill merge these 2 in - and get a build going on shared dev to test.

**Comment by KevinLynch569** [comment]
Can we make sure we are using the right regex for the compare?

**Comment by aastrong** [comment]
I have to test to do this. 
I'm fairly certain my regex is right - but there is no exact copy of the regex the transliteration is doing - php and js don't match up exactly like that. 

So i've created a test use case ( added to the read me ) - and if this case matches up - than all cases should match up ( and obviously ill be doing testing )

**Pull request merged**
